loglevel: INFO
source:
  db:
    type: postgres
    host: localhost
    port: 5432
    username: avnadmin
    password: PGPASSWORD
    dbname: db1
    qry: select first_name from employee order by first_name
target:
  db:
    type: oracle
    host: localhost
    port: 1521
    username: system
    password: ORAPASSWORD
    instance: XE
    qry: select first_name from employee order by first_name
