loglevel: INFO
max_delta: 3
source:
  name: src
  db:
    type: postgres
    host: localhost
    port: 5432
    username: postgres
    password: PGPASSWORD
    dbname: postgres
    qry: select a,b,c from t_test order by a
target:
  name: tgt
  db:
    type: oracle
    init_oracle_client: "/Users/PIERRE-MARIE/Downloads/instantclient_19_8"
    host: localhost
    port: 1521
    username: system
    password: ORAPASSWORD
    service_name: XE
    qry: select a,b,c from t_test order by a
