sudo: required
language: python
services:
    - docker
install: 
    - pip install -r requirements.txt
    - cd scribedb/example && docker-compose build 
    - docker-compose up -d
env:
    - DOCKER_COMPOSE_VERSION=1.25.4
before_install:
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - export COMMIT=${TRAVIS_COMMIT::7}
    - docker build -t ossdecathlon/scribedb:$COMMIT .
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
        branch: master