sudo: required
language: python
services:
    - docker
install: pip install -r requirements.txt
before_deploy:
    - docker build -t ossdecathlon/scribedb:$TRAVIS_TAG .
deploy:
    provider: script
    script: bash scripts/docker_push.sh
    on:
        branch: master