SET FEED OFF
SET VERIFY OFF
CONNECT &1/&2@'(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=&3)(PORT=1521))(CONNECT_DATA=(SID=XE)(SERVER=DEDICATED))))' 
COLUMN tab_count NEW_VALUE table_count
SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END tab_count FROM hr.departments;
EXIT table_count