name: release version

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        run: docker build -t decathlon/scribedb:${{ github.event.release.tag_name }} .

      - name: push
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push decathlon/scribedb:${{ github.event.release.tag_name }}


